spring:
    application:
        name: second-service
    rabbitmq:
        address: amqp://guest@127.0.0.1:15672/
        host: localhost
        port: 5672
        username: guest
        password: guest
        queue: greetings-sent
        exchange: Greetings
    mail:
        host: smtp.gmail.com
        port: 587
<<<<<<< HEAD
        username: ****************
        password: ****************
=======
        username: softfarmapp@gmail.com
        password: softfarm1651
>>>>>>> consumer
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
<<<<<<< HEAD

spring:
    application:
        name: second-service
=======
>>>>>>> consumer
server:
    port: 8082
eureka:
    instance:
        hostname: localhost
        port: 9000
    client:
        serviceUrl: 
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka